// Generated by CoffeeScript 1.10.0
(function() {
  var browsersync, gulp, server;

  gulp = require('gulp');

  server = require('gulp-develop-server');

  browsersync = require('browser-sync');

  gulp.task('server', function() {
    return server.listen({
      path: './bin/www'
    }, function() {
      return browsersync.init({
        proxy: 'http://localhost:3000'
      });
    });
  });

  gulp.task('serverrestart', function() {
    return server.restart(function() {
      return browsersync.reload();
    });
  });

  gulp.task('default', ['serverrestart'], function() {
    return gulp.watch(['./apps/app.js', './routes/*.js'], ['server-restart']);
  });

}).call(this);
