// Generated by CoffeeScript 1.10.0
(function() {
  var browsersync, gulp, nodemon, runSequence;

  gulp = require('gulp');

  nodemon = require('gulp-nodemon');

  runSequence = require('run-sequence');

  browsersync = require('browser-sync');

  gulp.task('default', function(callback) {
    return runSequence(['clean'], ['develop', 'brsync', 'watch'], callback);
  });

  gulp.task('clean', function(callback) {
    console.log('this is clean task .....');
    return callback();
  });

  gulp.task('develop', function() {
    return nodemon({
      script: './bin/www',
      ext: 'html ejs js',
      tasks: ['clean']
    }).on('restart', function() {
      return console.log('=========================restarted!');
    });
  });

  gulp.task('brsync', function() {
    return browsersync({
      proxy: 'http://localhost:3000',
      port: 8888,
      notify: true
    });
  });

  gulp.task('watch', function() {
    return gulp.watch(['./routes/**/*.js', './views/**/*.ejs', './public/css/style.css'], ['reload-server']);
  });

  gulp.task('reload-server', function(callback) {
    return runSequence(['develop'], ['bs-reload'], callback);
  });

  gulp.task('bs-reload', function() {
    return browsersync.reload();
  });

}).call(this);
