// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, ipspiders, superagent;

  superagent = require('superagent');

  cheerio = require('cheerio');

  ipspiders = function(type) {
    return this.type = type;
  };

  ipspiders();

  ipspiders.prototype = {
    agents: {
      xc: {
        gn: ['http://www.xicidaili.com/nt/', 'http://www.xicidaili.com/nn/'],
        gw: ['http://www.xicidaili.com/wn/', 'http://www.xicidaili.com/wt/']
      },
      td: {
        gn: ['http://www.kuaidaili.com/free/intr/'],
        gw: ['http://www.kuaidaili.com/free/outha/', 'http://www.kuaidaili.com/free/outtr/']
      }
    },
    getData: function(response) {
      var i, ips, len, page, ref;
      ips = [];
      ref = this.agents[this.type].gn;
      for (i = 0, len = ref.length; i < len; i++) {
        page = ref[i];
        console.log('================================^-^=======================');
        superagent.get(page).end(function(err, res) {
          var $;
          if (err) {
            console.error(err);
          } else {
            $ = cheerio.load(res.text);
            $('table tr').each(function() {
              var ip;
              ip = $(this).find('td:nth-child(1)').text().trim();
              if (ip) {
                return ips.push({
                  ip: ip,
                  port: $(this).find('td:nth-child(2)').text().trim(),
                  user: $(this).find('td:nth-child(3)').text().trim(),
                  pro: $(this).find('td:nth-child(4)').text().trim(),
                  dist: $(this).find('td:nth-child(5)').text().trim(),
                  time: $(this).find('td:nth-child(6)').text().trim(),
                  date: $(this).find('td:nth-child(7)').text().trim()
                });
              }
            });
          }
          console.log(ips);
          console.log('============================ips.length:');
          console.log(ips.length);
          return console.log(ips.length);
        });
      }
      return res.render('index', {
        title: 'Express'
      });
    }
  };

  module.exports = ipspiders;

}).call(this);
