// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, ipspiders, superagent;

  superagent = require('superagent');

  cheerio = require('cheerio');

  ipspiders = function(page) {
    return this.page = page;
  };

  ipspiders.prototype = {
    getData: function(response) {
      return superagent.get(this.page).end(function(err, res) {
        var $, iplists;
        if (err) {
          return console.error(err);
        } else {
          $ = cheerio.load(res.text);
          iplists = [];
          console.log("========================^_^======================");
          $('#ip_list tbody tr td').each(function() {
            return console.log($(this));
          });
          return console.log("========================^_^======================");
        }
      });
    }
  };

  module.exports = ipspiders;

}).call(this);
